import io

import streamlit as st
from PIL import Image

try:
    import pillow_heif
    pillow_heif.register_heif_opener()
except ImportError:
    pass

try:
    import pillow_avif  # noqa: F401  (registers AVIF opener on import)
except ImportError:
    pass

st.set_page_config(
    page_title="AI Image Detector",
    page_icon="🕵️",
    layout="wide",
    initial_sidebar_state="collapsed",
)

MODEL_NAME = "umm-maybe/AI-image-detector"
SUPPORTED_TYPES = ["jpg", "jpeg", "png", "webp", "avif", "heic"]
EXAMPLES = ["DALL·E (ChatGPT)", "Nano Banana (Gemini)", "Midjourney", "Ideogram"]

LABEL_DISPLAY = {
    "artificial": ("AI-Generated", "#ff4d6d"),
    "ai": ("AI-Generated", "#ff4d6d"),
    "fake": ("AI-Generated", "#ff4d6d"),
    "human": ("Likely Real", "#22c55e"),
    "real": ("Likely Real", "#22c55e"),
}


@st.cache_resource(show_spinner=False)
def load_classifier():
    from transformers import pipeline
    return pipeline("image-classification", model=MODEL_NAME)


def classify(image: Image.Image):
    clf = load_classifier()
    results = clf(image)
    results = sorted(results, key=lambda r: r["score"], reverse=True)
    return results


def display_name(raw_label: str):
    key = raw_label.strip().lower()
    return LABEL_DISPLAY.get(key, (raw_label.title(), "#a78bfa"))


st.markdown(
    """
    <style>
    .stApp {
        background-color: #0e0620;
        color: #e5e5f5;
    }
    h1.app-title {
        text-align: center;
        font-weight: 600;
        font-size: 1.6rem;
        margin-bottom: 2rem;
        color: #f2f2fa;
    }
    section[data-testid="stFileUploaderDropzone"] {
        background-color: #150b2e;
        border: 2px dashed #4c3a7a;
        border-radius: 14px;
    }
    div[data-testid="stFileUploader"] label { display: none; }
    .side-card {
        background-color: #170c33;
        border-radius: 14px;
        padding: 1.2rem 1.4rem;
        margin-bottom: 1rem;
    }
    .side-card h4 {
        margin-top: 0;
        margin-bottom: 0.9rem;
        font-size: 0.95rem;
        color: #f2f2fa;
    }
    .example-btn button {
        width: 100%;
        background-color: #201040 !important;
        color: #e5e5f5 !important;
        border: 1px solid #382a63 !important;
        border-radius: 10px !important;
        text-align: center !important;
        margin-bottom: 0.5rem;
    }
    .example-btn button:hover {
        border-color: #7c5cf0 !important;
        color: #ffffff !important;
    }
    .enterprise-box {
        text-align: center;
        color: #b8b3d1;
        font-size: 0.85rem;
        line-height: 1.4rem;
    }
    .enterprise-box a {
        color: #f2f2fa;
        font-weight: 600;
    }
    .footer-badge {
        text-align: center;
        margin-top: 2.5rem;
        color: #b8b3d1;
        font-size: 0.85rem;
    }
    .result-card {
        border-radius: 14px;
        padding: 1.2rem 1.4rem;
        background-color: #150b2e;
        margin-top: 1rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown('<h1 class="app-title">Check if an image was generated by AI</h1>', unsafe_allow_html=True)

if "selected_example" not in st.session_state:
    st.session_state.selected_example = None

left, right = st.columns([2, 1], gap="large")

with left:
    uploaded_file = st.file_uploader(
        "Upload or drag a file here",
        type=SUPPORTED_TYPES,
        label_visibility="collapsed",
    )

    if uploaded_file is None:
        st.markdown(
            """
            <div style="text-align:center; padding: 3.5rem 0; color:#b8b3d1;">
                <div style="font-size:2rem;">🖼️</div>
                <div style="font-size:1.1rem; font-weight:600; color:#f2f2fa; margin-top:0.6rem;">
                    Upload or drag a file here
                </div>
                <div style="font-size:0.85rem; margin-top:0.3rem;">
                    Supports JPG, JPEG, PNG, WebP, AVIF, HEIC
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
    else:
        image_bytes = uploaded_file.read()
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        st.image(image, caption=uploaded_file.name, use_container_width=True)

        with st.spinner("Analyzing image..."):
            try:
                results = classify(image)
            except Exception as e:
                st.error(f"Could not load or run the detection model: {e}")
                results = None

        if results:
            top_label, top_score = results[0]["label"], results[0]["score"]
            name, color = display_name(top_label)

            st.markdown(
                f"""
                <div class="result-card">
                    <div style="font-size:1.1rem; font-weight:700; color:{color};">
                        {name}
                    </div>
                    <div style="color:#b8b3d1; font-size:0.9rem; margin-top:0.2rem;">
                        Confidence: {top_score * 100:.1f}%
                    </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.progress(min(max(top_score, 0.0), 1.0))

            with st.expander("Full model output"):
                for r in results:
                    st.write(f"{r['label']}: {r['score'] * 100:.2f}%")

with right:
    st.markdown('<div class="side-card"><h4>Try these examples:</h4></div>', unsafe_allow_html=True)
    for ex in EXAMPLES:
        st.markdown('<div class="example-btn">', unsafe_allow_html=True)
        st.button(ex, key=f"ex_{ex}", disabled=True, help="Add sample images to enable this")
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown(
        """
        <div class="side-card enterprise-box">
            Need higher volume, dedicated support, and detection fine-tuned to
            your business? Our enterprise solutions deliver it.
            <br><br>
            <a href="#">Request a Demo</a>
        </div>
        """,
        unsafe_allow_html=True,
    )

st.markdown(
    '<div class="footer-badge">Built with Streamlit &middot; Powered by an open-source ML model &middot; For informational purposes only</div>',
    unsafe_allow_html=True,
)
